stages:
  split:
    cmd: python src/data/data_split.py
    deps:
    - data/raw_data
    - src/data/data_split.py
    outs:
    - data/processed_data
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed_data
    - src/data/normalize.py
    outs:
    - data/processed_data_scaled
  gridsearch:
    cmd: python src/data/grid_search.py
    deps:
    - data/processed_data
    - data/processed_data_scaled
    - src/data/grid_search.py
    - src/params
    outs:
    - src/params_output
  training:
    cmd: python src/models/training.py
    deps:
    - data/processed_data
    - data/processed_data_scaled
    - src/models/training.py
    - src/params_output
    outs:
    - src/models_output
  evaluate:
    cmd: python src/predicts/evaluate.py
    deps:
    - data/processed_data
    - data/processed_data_scaled
    - src/models_output
    - src/predicts/evaluate.py
    outs:
    - src/predicts_output
    metrics:
    - metrics/scores.json:
        cache: false
